### ISSUE TITLE
Jobs using SiteContextSwitcher

### ISSUE THREAD

**Issue by Trisco** [akshaysura/Sitecron#5]
When a job uses a SiteContextSwitcher or LanguageSwitcher to set the SiteContext & Culture, the CustomJobListener.JobWasExecuted finalization methods (SetItemStats f.i.) fail because the item only esxists in InvariantCulture, e.g.            
 Item jobItem = db.GetItem(new ID(itemID)) == null

**Comment by akshaysura** [comment]
Unfortunately, this issue is a bit more complicated. You have identified one of many things you could do in a job and it would be difficult to anticipate what we have to reset in order for the module to continue. It might be better for the job to reset the contexts in your case. Please let me know if you have additional comments.
